version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-minApi
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: CatalogoDatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  dotnet-app:
    image: mcr.microsoft.com/dotnet/sdk:6.0
    container_name: dotnet-minApi
    build:
      context: ./CatalogoApi
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=postgres;Database=CatalogoDatabase;Username=postgres;Password=postgres"
      Jwt__Key: "SuperSecretKey@345!"
      Jwt__Issuer: "CatalogoApi"
      Jwt__Audience: "CatalogoApi"
    ports:
      - "5000:5000"
    volumes:
      - ./CatalogoApi:/app
    working_dir: /app
    command: >
      sh -c "dotnet ef database update && dotnet run --urls http://0.0.0.0:5000"

volumes:
  postgres_data: